#!/bin/bash
set -x
VERSION="0.5.6"

echo "Downloading Zeppelin ${VERSION}..."
cd ${OPENSHIFT_DATA_DIR}
wget http://apache.arvixe.com/incubator/zeppelin/${VERSION}-incubating/zeppelin-${VERSION}-incubating-bin-all.tgz -O ${OPENSHIFT_DATA_DIR}zeppelin-${VERSION}-bundle.tar.gz
tar -xzf zeppelin-${VERSION}-bundle.tar.gz
rm -f zeppelin-${VERSION}-bundle.tar.gz
cd zeppelin-${VERSION}-incubating-bin-all/conf
mv zeppelin-site.xml.template zeppelin-site.xml
sed -i -e "s/0.0.0.0/$OPENSHIFT_DIY_IP/g" zeppelin-site.xml
sed -i -e "s#<configuration>#<configuration><property><name>zeppelin.websocket.port</name><value>8433</value><description>Websocket port</description></property>#g" zeppelin-site.xml
