#!/bin/bash
get_ZEPPELIN_ID() {
  local ZEPPELIN_ID='$(ps aux | grep [Z]eppelinServer | awk "{ print \$2 }")'
  echo "${ZEPPELIN_ID}"
  return ${ZEPPELIN_ID}
}

is_running() {
  local ZEPPELIN_ID="$(get_ZEPPELIN_ID)"
  if [ "${ZEPPELIN_ID}" != "" ]; then
    echo "true"
    return 0
  else
    echo "false"
    return 1
  fi
}

echo -n "Starting zeppelin"

cd ${OPENSHIFT_DATA_DIR}zeppelin-0.5.6-incubating-bin-all/bin

nohup ./zeppelin-daemon.sh start &

ZEPPELIN_ID="$(get_ZEPPELIN_ID)"
STARTCOUNT=1
while [ ${STARTCOUNT} -le 5 ]; do
  if [ "$(is_running)" == "false" ]; then
    echo -n '.'
    sleep 5
  else
    break
  fi
  START=$(( $STARTCOUNT + 1 ))
done
echo ''
if [ "$(is_running)" == "false" ]; then
  DAEMONPID=$(get_ZEPPELIN_ID)
  echo "Error! Zeppelin not started after 25 seconds!"
  exit 1
else
  echo "Zeppelin started"
  exit 0
fi
